import theRollingStones from './assets/images/theRollingStones.webp'

// export const allData = [
//     "THE BEATLES",
//     "RADIOHEAD",
//     "PINK FLOYD",
//     "LED ZEPPELIN",
//     "BOB DYLAN",
//     "DAVID BOWIE",
//     "METALLICA",
//     "BLACK SABBATH",
//     "THE ROLLING STONES",
//     "NEIL YOUNG",
//     "SONIC YOUTH",
//     "IRON MAIDEN",
//     "OPETH",
//     "THE CURE",
//     "KING CRIMSON",
//     "NIRVANA",
//     "THE WHO",
//     "PIXIES",
//     "TOM WAITS",
//     "THE DOORS",
//     "FRANK ZAPPA",
//     "THE SMITHS",
//     "SIGUR ROS",
//     "JIMI HENDRIX",
//     "TALKING HEADS",
//     "JOY DIVISION",
//     "ARCADE FIRE",
//     "NICK DRAKE",
//     "THE FLAMING LIPS",
//     "THE CLASH",
//     "TOOL",
//     "ELLIOTT SMITH",
//     "THE KINKS",
//     "PAVEMENT",
//     "GENESIS",
//     "THE BEACH BOYS",
//     "THE STOOGES",
//     "RUSH",
//     "SLAYER",
//     "ANIMAL COLLECTIVE",
//     "WILCO",
//     "THE WALKMEN",
//     "CAN",
//     "MY BLOODY VALENTINE",
//     "YES",
//     "ELVIS COSTELLO",
//     "BELLE AND SEBASTIAN",
//     "JUDAS PRIEST",
//     "PRIMUS",
//     "BRIAN ENO",
//     "NINE INCH NAILS",
//     "DEATH",
//     "PEARL JAM",
//     "THE WHITE STRIPES",
//     "BECK",
//     "JETHRO TULL",
//     "MEGADETH",
//     "WEEZER",
//     "MODEST MOUSE",
//     "VAN MORRISON",
//     "PJ HARVEY",
//     "RAMONES",
//     "MASTODON",
//     "DREAM THEATER",
//     "LOU REED",
//     "QUEEN",
//     "DEEP PURPLE",
//     "THE FALL",
//     "TALK TALK",
//     "OASIS",
//     "THE BYRDS",
//     "WIRE",
//     "THE NATIONAL",
//     "FAITH NO MORE",
//     "PRINCE",
//     "STEELY DAN",
//     "JEFF BUCKLEY",
//     "LOVE",
//     "TELEVISION",
//     "CAPTAIN BEEFHEART",
//     "INTERPOL",
//     "SIMON AND GARFUNKEL",
//     "ROXY MUSIC",
//     "XTC",
//     "COCTEAU TWINS",
//     "PETER GABRIEL",
//     "THE STROKES",
//     "YO LA TENGO",
//     "GUNS N ROSES",
//     "PULP",
//     "FUGAZI",
//     "KYUSS",
//     "JOHN LENNON",
//     "THE MARS VOLTA",
//     "HUSKER DU",
//     "FLEETWOOD MAC",
//     "BUILT TO SPILL",
//     "THE SHINS",
//     "ALICE IN CHAINS",
//     "SUFJAN STEVENS",
//     "DINOSAUR JR",
//     "KRAFTWERK",
//     "BLUR",
//     "CREAM",
//     "TV ON THE RADIO",
//     "THE STONE ROSES",
//     "NEW ORDER",
//     "THE BAND",
//     "PATTI SMITH",
//     "FUNKADELIC",
//     "DEAD KENNEDYS",
//     "AIR",
//     "BIG STAR",
//     "MOTORHEAD",
//     "THE ZOMBIES",
//     "SLINT",
//     "SLOWDIVE",
//     "CONVERGE",
//     "JEFFERSON AIRPLANE",
//     "PORTISHEAD",
//     "MOGWAI",
//     "SANTANA",
//     "DIRE STRAITS",
//     "GUIDED BY VOICES",
//     "SEX PISTOLS",
//     "GANG OF FOUR",
//     "T REX",
//     "MR BUNGLE",
//     "SPOON",
//     "ALICE COOPER",
//     "FLEET FOXES",
//     "IGGY POP",
//     "SEPULTURA",
//     "EMPEROR",
//     "VIOLENT FEMMES",
//     "VAN HALEN",
//     "ELTON JOHN",
//     "SWANS",
//     "PANTERA",
//     "EELS",
//     "THE MAGNETIC FIELDS",
//     "FAUST",
//     "OF MONTREAL",
//     "TESTAMENT",
//     "THIN LIZZY",
//     "PAUL SIMON",
//     "THE POGUES",
//     "TORTOISE",
//     "DARKTHRONE",
//     "PERE UBU",
//     "BATHORY",
//     "MINUTEMEN",
//     "PANDA BEAR",
//     "STEREOLAB",
//     "BJORK",
//     "MERCURY REV",
//     "GRATEFUL DEAD",
//     "JANES ADDICTION",
//     "OZZY OSBOURNE",
//     "LYNYRD SKYNYRD",
//     "BAUHAUS",
//     "TUPAC SHAKUR",
//     "NOTORIOUS BIG",
//     "JAY Z",
//     "NAS",
//     "EMINEM",
//     "RAKIM",
//     "KRS ONE",
//     "LL COOL J",
//     "ICE CUBE",
//     "PUBLIC ENEMY",
//     "NWA",
//     "WU TANG CLAN",
//     "OUTKAST",
//     "KANYE WEST",
//     "DR DRE",
//     "SNOOP DOGG",
//     "RUN DMC",
//     "BEASTIE BOYS",
//     "KENDRICK LAMAR",
//     "MISSY ELLIOTT",
//     "LIL WAYNE",
//     "COMMON",
//     "SCARFACE",
//     "DE LA SOUL",
//     "BIG DADDY KANE",
//     "DMX",
//     "MOS DEF",
//     "BUSTA RHYMES",
//     "J COLE",
//     "QUEEN LATIFAH",
//     "SALT N PEPA",
//     "GANG STARR",
//     "THE ROOTS",
//     "ICE T",
//     "THE FUGEES",
//     "BIG L",
//     "METHOD MAN",
//     "REDMAN",
//     "GHOSTFACE KILLAH",
//     "CYPRESS HILL",
//     "MOBB DEEP",
//     "BIZ MARKIE",
//     "THE PHARCYDE",
//     "NAUGHTY BY NATURE",
//     "FAT JOE",
//     "TALIB KWELI",
//     "LUPE FIASCO",
//     "CHANCE THE RAPPER",
//     "CHILDISH GAMBINO",
//     "TYLER THE CREATOR",
//     "LIL KIM",
//     "TRICKY",
//     "REMY MA",
//     "CARDI B",
//     "YOUNG THUG",
//     "DRAKE",
//     "TRAVIS SCOTT",
//     "ASAP ROCKY",
//     "LOGIC",
//     "JOEY BADASS",
//     "KILLER MIKE",
//     "BIG SEAN",
//     "PUSHA T",
//     "WIZ KHALIFA",
//     "MEEK MILL",
//     "NICKI MINAJ",
//     "LIL UZI VERT",
//     "FUTURE",
//     "BIG BOI",
//     "RZA",
//     "THE GAME",
//     "NATE DOGG",
//     "LUDACRIS",
//     "JADAKISS",
//     "Q TIP",
//     "SLICK RICK",
//     "SCHOOLBOY Q",
//     "GZA",
//     "KID CUDI",
//     "EARL SWEATSHIRT",
//     "FREDDIE GIBBS",
//     "MF DOOM",
//     "YOUNG JEEZY",
//     "AFRIKA BAMBAATAA",
//     "G EAZY",
//     "JOHNNY CASH",
//     "ALANIS MORISSETTE",
//     "ALVVAYS",
//     "ALTIN GUN",
//     "APHEX TWIN",
//     "BELLY",
//     "THE BETA BAND",
//     "THE BETHS",
//     "BIG THIEF",
//     "BLOC PARTY",
//     "BOARDS OF CANADA",
//     "BON IVER",
//     "BRAND NEW",
//     "THE BREEDERS",
//     "BRIGHT EYES",
//     "BROADCAST",
//     "BULLY",
//     "CARSICK CARS",
//     "CAT POWER",
//     "CHARLY BLISS",
//     "COM TRUISE",
//     "COURTNEY BARNETT",
//     "CURTIS MAYFIELD",
//     "THE DANDY WARHOLS",
//     "DANNY BROWN",
//     "DEAFHEAVEN",
//     "DEERHUNTER",
//     "DEFTONES",
//     "DIIV",
//     "DIRTY PROJECTORS",
//     "DRY CLEANING",
//     "DUSTER",
//     "EARTHGANG",
//     "ELDER",
//     "EMMA RUTH RUNDLE",
//     "FEIST",
//     "FLYING LOTUS",
//     "FUTURE ISLANDS",
//     "GRANDADDY",
//     "GREEN DAY",
//     "GRIZZLY BEAR",
//     "GROUPER",
//     "HEATMISER",
//     "HELIUM",
//     "THE HOLD STEADY",
//     "HOLE",
//     "HOP ALONG",
//     "HUM",
//     "INDIGO DE SOUZA",
//     "IRON AND WINE",
//     "JAMES BLAKE",
//     "JAPANESE BREAKFAST",
//     "JEFF ROSENSTOCK",
//     "JIMMY EAT WORLD",
//     "JOANNA NEWSOM",
//     "JOHN PRINE",
//     "JONI MITCHELL",
//     "JUSTICE",
//     "THE KILLERS",
//     "THE KILLS",
//     "THE KNIFE",
//     "LANA DEL REY",
//     "MASSIVE ATTACK",
//     "MAZZY STAR",
//     "MITSKI",
//     "MJ LENDERMAN",
//     "THE MOUNTAIN GOATS",
//     "NELLY",
//     "NO AGE",
//     "PHOEBE BRIDGERS",
//     "PHOENIX",
//     "PINEGROVE",
//     "PRIESTS",
//     "PUP",
//     "RADIATOR HOSPITAL",
//     "RATATAT",
//     "RATBOYS",
//     "REAL ESTATE",
//     "REGINA SPEKTOR",
//     "RIDE",
//     "RILO KILEY",
//     "RINGO DEATHSTARR",
//     "SCREAMING FEMALES",
//     "SHLOHMO",
//     "SLEIGH BELLS",
//     "SLIFT",
//     "SLOW PULP",
//     "THE SMILE",
//     "SNAIL MAIL",
//     "SOFT KILL",
//     "SPEEDY ORTIZ",
//     "SQUID",
//     "ST VINCENT",
//     "SUPER FURRY ANIMALS",
//     "SWIRLIES",
//     "TAME IMPALA",
//     "TEGAN AND SARA",
//     "THEE OH SEES",
//     "THE THERMALS",
//     "THOM YORKE",
//     "TITUS ANDRONICUS",
//     "TOM PETTY",
//     "TY SEGALL",
//     "TYCHO",
//     "VAMPIRE WEEKEND",
//     "THE VASELINES",
//     "VERUCA SALT",
//     "WOLF PARADE",
//     "YEAH YEAH YEAHS",
//     "YUCK",
//     "SHANIA TWAIN",
//     "GARTH BROOKS",
//     "GEORGE STRAIT",
//     "ALAN JACKSON",
//     "REBA MCENTIRE",
//     "TIM MCGRAW",
//     "KENNY CHESNEY",
//     "JOHN DENVER",
//     "THE CHICKS",
//     "WILLIE NELSON",
//     "BROOKS AND DUNN",
//     "FAITH HILL",
//     "TOBY KEITH",
//     "LUKE COMBS",
//     "LUKE BRYAN",
//     "CHRIS STAPLETON",
//     "BLAKE SHELTON",
//     "CARRIE UNDERWOOD",
//     "ELVIS PRESLEY",
//     "EAGLES",
//     "MICHAEL JACKSON",
//     "BILLY JOEL",
//     "MARIAH CAREY",
//     "MADONNA",
//     "WHITNEY HOUSTON",
//     "CELINE DION",
//     "JOURNEY",
//     "TAYLOR SWIFT",
//     "NEIL DIAMOND",
//     "ALABAMA",
//     "KENNY G",
//     "KENNY ROGERS",
//     "BOB SEGER",
//     "ERIC CLAPTON",
//     "CHICAGO",
//     "BRITNEY SPEARS",
//     "BEYONCE",
//     "FOREIGNER",
//     "ROD STEWART",
//     "BACKSTREET BOYS",
//     "DEF LEPPARD",
//     "BON JOVI",
//     "PHIL COLLINS",
//     "JAMES TAYLOR",
//     "USHER",
//     "BOSTON",
//     "LINKIN PARK",
//     "ADELE",
//     "BEE GEES",
//     "NSYNC",
//     "JOHN MELLENCAMP",
//     "FRANK SINATRA",
//     "LUTHER VANDROSS",
//     "ENYA",
//     "STEVE MILLER BAND",
//     "JANET JACKSON",
//     "RIHANNA",
//     "CREED",
//     "HOOTIE AND THE BLOWFISH",
//     "MOTLEY CRUE",
//     "ZZ TOP",
//     "REO SPEEDWAGON",
//     "THE CARPENTERS",
//     "JUSTIN BIEBER",
//     "NICKELBACK",
//     "ARIANA GRANDE",
//     "POST MALONE",
//     "THE WEEKND",
//     "KATY PERRY",
//     "IMAGINE DRAGONS",
//     "ED SHEERAN",
//     "BRUNO MARS",
//     "JUICE WRLD",
//     "LADY GAGA",
//     "SZA",
//     "MILEY CYRUS",
//     "FALL OUT BOY",
//     "TWENTY ONE PILOTS",
//     "FLO RIDA",
//     "HARRY STYLES",
//     "PITBULL",
//     "QUASIMOTO",
//     "FABOLOUS",
//     "FLATBUSH ZOMBIES",
//     "MAC MILLER",
//     "BLACK HIPPY",
//     "AB SOUL",
//     "DENZEL CURRY",
//     "MEECHY DARKO",
//     "NIPSY HUSTLE",
//     "MADLIB",
//     "ANDERSON PAAK",
//     "DOJA CAT",
//     "LIZZO",
//     "ASHANTI",
//     "JA RULE",
//     "BLAQUE",
//     "GINUWINE",
//     "CIARA",
//     "SELENA GOMEZ",
//     "OLIVIA RODRIGO",
//     "JUSTIN TIMBERLAKE",
//     "CHRISTINA AGUILERA",
//     "DESTINYS CHILD",
//     "SPICE GIRLS",
//     "CHRIS LIBERATOR",
//     "JEFF MILLS",
//     "KEVIN SAUNDERSON",
//     "DEEP CHORD",
//     "OLIVER LIEB",
//     "BASIC CHANNEL",
//     "PLASTIKMAN",
//     "DREXCIYA",
//     "LUKE VIBERT",
//     "GOLDIE",
//     "CAPTAIN TINRIB",
//     "SKREAM",
//     "FLOATING POINTS",
//     "FOUR TET",
//     "PHOTEK",
//     "MUDDY WATERS",
//     "ROBERT JOHNSON",
//     "BUDDY GUY",
//     "LUDWIG VAN BEETHOVEN",
//     "WOODY GUTHRIE",
//     "MILES DAVIS",
//     "MINISTRY",
//     "GAAHLS WYRD",
//     "GOJIRA",
//     "VENOM",
//     "WATAIN",
//     "DEICIDE",
//     "KNOCKED LOOSE",
//     "HIGH ON FIRE",
//     "OBITUARY",
//     "AT THE GATES",
//     "MAYHEM",
//     "ELECTRIC WIZARD",
//     "CANNIBAL CORPSE",
//     "ENTOMBED",
//     "CRADLE OF FILTH",
//     "SLIPKNOT",
//     "DANZIG",
//     "GWAR",
//     "ANTHRAX",
//     "IN FLAMES",
//     "SATYRICON",
//     "CATHEDRAL",
//     "TYPE O NEGATIVE",
//     "NAPALM DEATH",
//     "SLEEP",
//     "CARCASS",
//     "RAMMSTEIN",
//     "LAMB OF GOD",
//     "KILLSWITCH ENGAGE",
//     "MESHUGGAH",
//     "BARONESS",
//     "CAVE IN",
//     "MUDVAYNE",
//     "PIG DESTROYER",
//     "BOLT THROWER",
//     "HATEBREED",
//     "AMON AMARTH",
//     "UNDEROATH",
//     "POWER TRIP",
//     "CHELSEA WOLFE",
//     "RED FANG",
//     "OLD MAN GLOOM",
//     "WINDHAND",
//     "AALIYAH",
//     "MARK MORRISON",
//     "MONTELL JORDAN",
//     "LAURYN HILL",
//     "BRANDY",
//     "TEVIN CAMPBELL",
//     "EN VOGUE",
//     "COLOR ME BADD",
//     "MARY J BLIGE",
//     "TONI BRAXTON",
//     "KEITH SWEAT",
//     "BRIAN MCKNIGHT",
//     "ERYKAH BADU",
//     "JODECI",
//     "FAITH EVANS",
//     "JANELLE MONAE",
//     "ARI LENNOX",
//     "LIONEL RICHIE",
//     "CHAKA KHAN",
//     "NEW EDITION",
//     "MARVIN GAYE",
//     "ARETHA FRANKLIN",
//     "OTIS REDDING",
//     "SAM COOKE",
//     "FOUR TOPS",
//     "JAMES BROWN",
//     "STEVIE WONDER",
//     "THE SUPREMES",
//     "SMOKEY ROBINSON",
//     "THE ISLEY BROTHERS",
//     "RAY CHARLES",
//     "DIANA ROSS",
//     "ETTA JAMES",
//     "THE DELFONICS",
//     "ISAAC HAYES",
//     "GLADYS KNIGHT",
//     "AL GREEN",
//     "BILL WITHERS",
//     "RUFUS",
//     "THE STAPLE SINGERS",
//     "BARRY WHITE",
//     "OHIO PLAYERS",
//     "THE COMMODORES",
//     "BOBBY WOMACK",
//     "TINA TURNER",
//     "THE EMOTIONS",
//     "WAR",
//     "ROBERTA FLACK",
//     "THE STYLISTICS",
//     "JOHN COLTRANE",
//     "GEORGE BENSON",
//     "HERBIE HANCOCK",
//     "STAN GETZ",
//     "JOAO GILBERTO",
//     "CHET BAKER",
//     "DAVE BRUBECK",
//     "BILL EVANS",
//     "ALICE COLTRANE",
//     "CHARLES MINGUS",
//     "KEITH JARRETT",
//     "TONY ALLEN",
//     "MARY LOU WILLIAMS",
//     "SUN RA",
//     "DUKE ELLINGTON",
//     "ELLA FITZGERALD",
//     "DIZZY GILLESPIE",
//     "CHARLIE PARKER",
//     "THELONIOUS MONK",
//     "SUNNY ROLLINS",
//     "NAT KING COLE",
//     "DEAN MARTIN",
//     "LOUIS ARMSTRONG",
//     "BING CROSBY",
//     "NINA SIMONE",
//     "BILLIE HOLIDAY",
//     "FATS WALLER",
//     "DJANGO REINHARDT",
//     "EARTHA KITT",
//     "JOHN LEE HOOKER",
//     "HOWLIN WOLF",
//     "BB KING",
//     "ALBERT KING",
//     "LIGHTNIN HOPKINS",
//     "WILLIE DIXON",
//     "ELMORE JAMES",
//     "STEVIE RAY VAUGHAN",
//     "ETTA JAMES",
//     "SON HOUSE",
//     "BO DIDDLEY",
//     "BIG MAMA THORNTON",
//     "BESSIE SMITH",
//     "TAJ MAHAL",
//     "JOHN MAYALL",
//     "SKIP JAMES",
//     "MA RAINEY",
//     "MGMT",
//     "WEYES BLOOD",
//     "MAC DEMARCO",
//     "ARCTIC MONKEYS",
//     "ANGEL OLSEN",
//     "KURT VILE",
//     "CHVRCHES",
//     "PERFUME GENIUS",
//     "CARIBOU",
//     "IDLES",
//     "SKY FERREIRA",
//     "BOYGENIUS",
//     "ORVILLE PECK",
//     "DESTROYER",
//     "KING KRULE",
//     "CAR SEAT HEADREST",
//     "THE XX",
//     "BLOOD ORANGE",
//     "TORO Y MOI",
//     "FKA TWIGS",
//     "PARQUET COURTS",
//     "SOCCER MOMMY",
//     "PURITY RING",
//     "THE POSTAL SERVICE",
//     "PASSION PIT",
//     "HOT CHIP",
//     "GIRLS",
//     "MY MORNING JACKET",
//     "BEIRUT",
//     "LADYTRON",
//     "CHAIRLIFT",
//     "FRANZ FERDINAND",
//     "THE LIBERTINES",
//     "HOT HOT HEAT",
//     "SANTIGOLD",
//     "BAT FOR LASHES",
//     "FRIGHTENED RABBIT",
//     "DOVES",
//     "MATT AND KIM",
//     "BAND OF HORSES",
//     "CAMERA OBSCURA",
//     "BATTLES",
//     "LE TIGRE",
//     "CLAUDE DEBUSSY",
//     "JOHANNES BRAHMS",
//     "IGOR STRAVINSKY",
//     "JOHN ADAMS",
//     "LOUISE FARRENC",
//     "FREDERIC CHOPIN",
//     "BENJAMIN BRITTEN",
//     "GEORGE ENESCU",
//     "GEORG PHILIPP TELEMANN",
//     "SERGEI PROKOFIEV",
//     "CARL NIELSEN",
//     "RICHARD STRAUSS",
//     "ROBERT SCHUMANN",
//     "CECILE CHAMINADE",
//     "BEDRICH SMETANA",
//     "JOHN WILSON",
//     "MOBY",
//     "FATBOY SLIM",
//     "BASEMENT JAXX",
//     "AUTECHRE",
//     "DEPECHE MODE",
//     "DJ SHADOW",
//     "DR OCTAGON",
//     "THE AVALANCHES",
//     "HOT CHIP",
//     "FEVER RAY",
//     "ULRICH SCHNAUSS",
//     "CHROMEO",
//     "CRYSTAL CASTLES",
//     "FLUME",
//     "ODESZA",
//     "JAMIE XX",
//     "SKRILLEX",
//     "MAJOR LAZER",
//     "BURIAL",
//     "NICOLAS JAAR",
//     "LINDSTROM",
//     "YVES TUMOR",
//     "CLAMS CASINO",
//     "MOUNT KIMBIE",
//     "NOSAJ THING",
//     "PURITY RING",
//     "TOWNES VAN ZANDT",
//     "IRIS DEMENT",
//     "BOB DYLAN",
//     "GRAM PARSONS",
//     "LEONARD COHEN",
//     "PETE SEEGER",
//     "PHIL OCHS",
//     "NICK DRAKE",
//     "JOAN BAEZ",
//     "DONOVAN",
// ]

export const allData = [
    "THE ROLLING STONES",
    "LED ZEPPELIN",
    "THE KINKS",
    "BUILT TO SPILL",
    "DINOSAUR JR",
    "PAVEMENT",
    "NIRVANA",
    "THE SMITHS",
    "JIMI HENDRIX",
    "BOARDS OF CANADA"
]

export const allDataObject = {
    "THE ROLLING STONES": { image: theRollingStones, bio: `It wasn’t that rock music didn’t exist before The Rolling Stones—it did. But it didn’t exist at quite the same scale, or with the same reach, or with the same sheer attitude that made the Stones so seismic. You wonder if it had something to do with their otherness, as though the fact that the American sounds they emulated—blues, country, R&B—didn’t belong to them made them both more reverential and more free to explore. Like excavations from an archaeological dig, the band’s best music played out like a conversation between present and past, finding fresh meaning and connections in sounds that feel classic, bygone. Mick Jagger once said he’d rather be dead than singing “Satisfaction” at 45. Certainly there were other artists of his generation who took the same attitude, figuratively and otherwise. Un-rock as it may be, The Rolling Stones decided to live. Formed in 1962, the band—which went on to include guitarist Keith Richards, jazz drummer Charlie Watts and bassist Bill Wyman, among others—became one of the spearheads of the British Invasion, bad boys to The Beatles’ teddy bears. They toyed with folk and psychedelia in the mid-’60s (“Ruby Tuesday,” “Mother’s Little Helper”) but always circled back to something grittier, darker. With some exceptions (including The Beatles’ famous live farewell at Shea Stadium), the idea of “arena rock” didn’t really exist until The Stones: There wasn’t the infrastructure, the technical capacity. As classic as their late-’60s and ’70s albums are (the country sprawl of Beggars Banquet and Exile On Main St., the swagger of Some Girls), they made their legacy on stage, scaling up the sweaty rush of small clubs to hockey rinks and football stadiums, using the studio as a place to refine instead of retreat. In commemoration of Mick Jagger’s 75th birthday, a German entomologist persuaded his colleagues to name several fossils after members of the band—a singular tribute, not to mention a loving jab at their longevity. Even death itself never stopped the Stones. After Watts passed in 2021, they kept touring, with Steve Jordan filling the founding drummer’s sizable shoes. And in 2023, they honored his memory by releasing their last sessions with him on their 28th studio album, Hackney Diamonds. With a stellar guest list including Stevie Wonder, Paul McCartney, Elton John, and Lady Gaga, the record went to No. 1 in multiple countries. And in April 2024, The Stones mounted a three-month North American tour, which was Mick and Keith’s first trek as octogenarians. But the outing made it clear to the world that the ultimate OGs of rock ’n’ roll were as full of fire as ever.` },
    "LED ZEPPELIN": { image: "https://www.rollingstone.com/wp-content/uploads/2024/12/Led-Zeppelin-Doc-Trailer.jpg?w=1581&h=1054&crop=1", bio: `It wouldn’t be entirely accurate to say Led Zeppelin invented heavy metal. Formed by latter-day Yardbirds guitarist Jimmy Page in 1968 (originally as The New Yardbirds), the quartet were among a wave of bands taking the blues-based British Invasion sound in a louder direction. However, no other group wielded their might with such an authoritative sense of groove and grandeur. In Page’s hands, blues-based riffs became as wildly complex as his solos, while the rhythm section featured a drummer (John Bonham) whose kick-pedal could leave craters and a secret-weapon bassist (John Paul Jones) who served as the industrial-strength glue that held it all together. If heaviness was Zeppelin’s only attribute, their place in rock history would still be assured. But their thundering sound was always balanced by a disarming delicacy—best exemplified by the quiet-to-loud ascension of their perennial classic-rock-radio countdown winner, “Stairway to Heaven.” Sure, the group’s golden-god frontman, Robert Plant, possessed a shriek that could summon a fleet of rampaging Vikings (see: 1970’s “Immigrant Song”). But his obsession with psychedelic-folk acts like The Incredible String Band yielded a deep well of tender acoustic serenades, and he swiftly outgrew the girl-done-me-wrong narratives of the blues to weave Tolkien-esque tales that presaged metal’s fascination with medieval mythology. Plus, Page was not only a redoubtable riff machine, but a visionary producer who reimagined the rock album as a widescreen war epic. You can hear that cinematic sensibility take root in the brain-scrambling breakdown of “Whole Lotta Love” (as avant-garde as blues-rock boogie could get in 1969) and achieve its apex on 1975’s “Kashmir,” an epic Eastern-inspired odyssey where Jones’ sinister, Mellotron-manipulated string arrangement proved heavier than any guitar-powered rocker in their repertoire. Zeppelin seemed to be entering a fascinating new phase with 1979’s synth-injected In Through the Out Door, before Bonham’s untimely death a year later brought the band to a sudden end. But through the hair-band wailers of ‘80s, the militant rap-metal of Rage Against the Machine, the battered blues of The White Stripes, and the 21st-century swagger of Greta Van Fleet, the aftershocks of Led Zeppelin’s seismic ’70s canon reverberate forevermore.` },
    "THE KINKS": { image: "https://thestrangebrew.co.uk/wp-content/uploads/2012/12/Kinks.jpg", bio: `If all that The Kinks contributed to the rock ‘n’ roll canon was the riff to 1964’s “You Really Got Me,” they’d still be legends today. With those nasty, distorted guitar chords, the London group (formed a year prior) transformed the British Invasion into a genuine act of war, teaching the first generations of punks and metalheads how to turn it up to 11. However, the violence implicit in The Kinks’ early music tended to manifest in actual onstage fisticuffs (often between frontman Ray Davies and his guitarist brother Dave), saddling the group with a rough-cat reputation that would see them denied touring visas for the U.S. from 1965 to 1970. While that setback prevented The Kinks from achieving the stadium-conquering stardom of The Beatles and The Rolling Stones, they swiftly transformed from the most unruly rock band of the era into the most erudite. They became the rare British Invasion group to speak specifically to the experience of being British, with Ray perfecting a signature blend of romantic Londontown poetry (“Waterloo Sunset”) and scathing upper-class satire (“Sunny Afternoon”) that had him wrapping himself in the Union Jack one moment and burning it the next. And he didn’t just prod at high-society norms, but at the male-dominated culture underpinning them: With 1970’s “Lola,” he delivered an uncommon celebration of gender-bending in a pre-glam landscape. While peers like The Who experimented with the rock-opera format, The Kinks made the theatrical concept album their raison d’etre throughout the ’70s—often at the expense of their commercial prospects—though later singles like 1981’s hard-rockin’ “Destroyer” and 1983’s music-hall fantasia “Come Dancing” proved they could sneak onto the charts when the mood struck. The Kinks officially disbanded in 1997—but then, thanks to spiritual descendents like Damon Albarn and Arctic Monkeys, they’ve never really gone away. ` },
    "BUILT TO SPILL": { image: "https://subpop-img.s3.amazonaws.com/asset/artist_images/attachments/000/009/973/max_600_400/builttospill-2023-promo-01-isabelageorgetti-2284x1500-300.jpg?1680560615", bio: `Led by guitarist and songwriter Doug Martsch, Built to Spill bring together the flinty riffs and abstract lyrics of indie rock with guitar heroics worthy of packed arenas. Formed in 1992 in Boise, ID, by Martsch (formerly of indie-proggers Treepeople), Built to Spill released their first album, Ultimate Alternative Wavers, a year later. After a few more releases and lineup rotations, as well as a stint on Lollapalooza 1995, the band signed to Warner Bros.; their first release under that deal, 1997’s sprawling, introspective Perfect from Now On, was a triumph, a best-case scenario of major-label money bolstering grand artistic intentions. Its 1999 follow-up, Keep It Like a Secret, applied Built to Spill’s formula to pop gems like the stirring “The Plan.” From there, Martsch and an ever-shifting cast of musicians released ambitious albums like 2001’s cavernous Ancient Melodies of the Future and 2015’s pensive Untethered Moon and toured frequently. In 2021 Built to Spill—now the trio of Martsch, bassist Melanie Radford, and drummer Teresa Esguerra—signed to Sub Pop, with their first release for the storied indie, When the Wind Forgets Your Name, coming out the following September.` },
    "DINOSAUR JR": { image: "https://deafdogsrock.com/wp-content/uploads/2011/07/cute-puppy-dog-wallpapers.jpg", bio: `Dinosaur Jr. are one of the loudest rock bands around—fitting, since vocalist/guitarist J Mascis once described the group’s music as “ear-bleeding country.” The Amherst, MA, group formed in 1984, after the dissolution of Mascis’ hardcore band Deep Wound, which also featured bassist Lou Barlow. Early support from Sonic Youth after the 1985 release of Dinosaur buoyed the band, and they had a major UK hit in 1988 with the noisy, jangly “Freak Scene.” American success followed with the ’90s rise of grunge, as fuzz-coated singles such as “Start Choppin’” and the irreverent “Feel the Pain” connected with modern-rock fans. Dinosaur Jr. split in 1997 but regrouped in 2005 with Barlow—who had exited the band amid acrimony before their major success—and picked up right where they left off. The band, which also featured erstwhile drummer Murph, issued well-received albums (including 2021’s Sweep It Into Space) and kicked out the loud jams on extensive tours.` },
    "PAVEMENT": { image: "https://deafdogsrock.com/wp-content/uploads/2011/07/cute-puppy-dog-wallpapers.jpg", bio: `If the indie-rock boom of the early '90s has a boy band, it’s Pavement: The sweet melodies, the carefree delivery, they way they can be the smartest guys in the room without making a point of it. At a time when some of their post-punk peers were still waging musical revolution, they embraced the rosy warmth of classic rock (Crooked Rain, Crooked Rain), and even at their most challenging (Westing (By Musket and Sextant, the stoned sprawl of Wowee Zowee) were more playful than rebellious, the sound of collegiate guys who liked sports and poetry in equal measure, who were always interesting but never pretentious. Courtney Love once described their frontman, Steve Malkmus, as “the Grace Kelly of indie rock”—an invocation not only of the band’s charm, but their poise and effortlessness. Pavement weren’t naive. But they sounded like winners without even playing the game.

    Their early music (1992’s Slanted and Enchanted in particular) summarized the best of ‘80s underground rock (the poetry of R.E.M., noise of Sonic Youth, sloppiness of The Replacements) while adding their own sweet-and-sour essence, turning out songs that transformed oblique poetry and fragmented of noise into lighters-up anthems (“In the Mouth a Desert,” “Trigger Cut”). Malkmus once joked that he realized he’d never be a real punk when he saw Henry Rollins of Black Flag squeeze a cue ball as a pre-show warmup. But even as their sound mellowed, the band retained an irreverence, delivering their grandest music—“Grounded,” “Type Slowly,” “The Hexx”—with a looseness that made them look humble: Not rock gods, but regular dudes you kinda wanted to root for. The band broke up after 1999’s Terror Twilight, reforming in 2010 and sporadically since.` },
    "NIRVANA": { image: "https://deafdogsrock.com/wp-content/uploads/2011/07/cute-puppy-dog-wallpapers.jpg", bio: `Even now, years after you first felt its edges, the chorus of “Smells Like Teen Spirit” still sounds too dangerous—too loud, too ugly, too upset—for any mainstream. And yet, Nirvana’s 1991 single didn’t just mark an unlikely breakthrough for the Seattle trio, it upended popular culture in ways we’ve haven’t seen since. Punk became pop, grunge became global vernacular, industry walls became rubble, and frontman Kurt Cobain became the reluctant voice of a generation in need of catharsis, all seemingly overnight. Though his 1994 suicide would see the band dissolve just as abruptly as they’d arrived, their story is now rock’n’roll parable and their influence still felt—as punks, icons, Hall of Famers, purveyors of haunting melody and often terrifying noise. ` },
    "THE SMITHS": { image: "https://deafdogsrock.com/wp-content/uploads/2011/07/cute-puppy-dog-wallpapers.jpg", bio: `The Smiths were the definitive British indie rock band of the '80s, marking the end of synth-driven new wave and the beginning of the guitar-based rock that dominated English rock into the '90s. The group's core members, vocalist Morrissey and guitarist Johnny Marr, were obsessive rock fans inspired by the D.I.Y. ethics of punk, but they also had a fondness for girl groups, pop, and rockabilly. They also represented one of the strangest collaborative teams in rock history: Marr was the rock traditionalist, meticulously layering his guitar tracks in the studio. Morrissey, on the other hand, embraced the forlorn, romantic poetry of Oscar Wilde. While it led to the Smiths' early demise, their friction resulted in a flurry of music that provided the blueprint for British rock in the following decade.` },
    "JIMI HENDRIX": { image: "https://faroutmagazine.co.uk/static/uploads/1/2023/03/Jimi-Hendrix-in-colour-Copenhagen-1967-Bent-Rej-Far-Out-Magazine-F-1140x855.jpg", bio: `About a week before Jimi Hendrix’s death in September 1970, an interviewer asked about his role in the invention of psychedelic music. Hendrix, who was as soft-spoken offstage as he was incendiary on it, laughed. Sure, you could call it psychedelic if you wanted: the trippy imagery; the wild, loud performances. But more than psychedelic, he explained, he was trying to get across what he called “a clash between fantasy and reality.” From the beginning, his music captured the outer reaches of a counterculture turning on to new chemicals, sounds, feelings, and social possibilities (“Purple Haze,” “Are You Experienced?”). But it also remained grounded in traditions of Black music carried over from his days as a guitarist on the chitlin circuit—blues, yes, but also smooth, Chicago-style R&B (“Have You Ever Been [To Electric Ladyland]”), the syncopations of funk (“Fire,” “Freedom”), and the naked expressivity of Southern soul (“The Wind Cries Mary”). No matter how adventurous he got (and how unprecedented he sounded), Jimi Hendrix came from—and spoke to—Earth.

    Born John Allen Hendrix in Seattle in 1942 (and later renamed James Marshall Hendrix by his parents), he started his career as a sideman for artists like The Isley Brothers and Little Richard before moving to England in 1966, where he became an instant legend. (Everyone—Eric Clapton, Pete Townshend, Jeff Beck, everyone—has a story about the first time they saw Hendrix; Keith Richards later joked that in creating a style that nobody could copy but that inspired everyone to try, Hendrix nearly ruined the guitar.) In two years, he recorded three albums that set new standards for what blues-based rock could be. He made druggy, mind-bending music that came across like pop (1967’s Are You Experienced) and helped redefine the rock album as a kind of stylistic playground where artists could contrast moods, explore curiosities, and stretch their creative visions (1968’s Electric Ladyland). At the heart of even his fieriest music was a gentleness that registered, above all, as spiritual curiosity. A poem he wrote a few hours before his death in 1970 featured the lines “the story of life is quicker than the wink of an eye/The story of love is hello and goodbye.”` },
    "BOARDS OF CANADA": { image: "https://deafdogsrock.com/wp-content/uploads/2011/07/cute-puppy-dog-wallpapers.jpg", bio: `Boards of Canada’s music feels like a transmission from a parallel universe: The reference points (ambient, hip-hop, shoegaze) are recognizable enough to be familiar, but the signal has gotten garbled on the trip between dimensions, lending a mysterious, uncanny cast to the duo’s sound. Born in Scotland in the early ‘70s, brothers Michael Sandison and Marcus Eoin began making music together as teens in Edinburgh, and for their first official release, 1996’s Hi Scores, they named themselves in homage to the National Film Board of Canada, whose nature documentaries influenced their music’s washed-out colors and warbly sonics. Since Music Has the Right to Children, bliss and paranoia have struck an uneasy truce in Boards’ productions, which are shot through with murky samples and cryptic references—evidence, fans say, of hidden mysteries just waiting to be decoded.` }
  };